-- supabase/migrations/YYYYMMDDHHMMSS_create_babu_rao_table.sql

CREATE TABLE public."babu-rao" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym text,
    fit text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- RLS Policy for the new table
ALTER TABLE public."babu-rao" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public."babu-rao"
FOR SELECT
USING (true);

CREATE POLICY "Allow individual insert access" ON public."babu-rao"
FOR INSERT
WITH CHECK (true);
