name: Supabase Push CI

on:
  push:
    branches:
      - main

jobs:
  push-to-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Push Database Migrations
        run: supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --yes
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
